services:
  app1:
    build: .
    environment:
      UDS_PATH: /sockets/app1.sock
    volumes:
      - backend-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "150MB"

  app2:
    build: .
    environment:
      UDS_PATH: /sockets/app2.sock
    volumes:
      - backend-sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.475"
          memory: "150MB"

  lb:
    image: haproxy:3.1-alpine
    entrypoint: ["haproxy", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
    ports:
      - "9999:9999"
    volumes:
      - backend-sockets:/sockets
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "16MB"

volumes:
  backend-sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=4m,mode=0777
